# https://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci_sum_even(limit):
    # a is the current number, b is the next number
    a, b = 1, 1
    even_sum = 0

    while a <= limit:
        if a % 2 == 0:
            even_sum += a
        a, b = b, a + b
    return even_sum


def main():
    limit = 4000000
    result = fibonacci_sum_even(limit)
    print(result)  # 4613732


if __name__ == "__main__":
    main()
